# Generated by Django 5.2.4 on 2025-07-23 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_student_studentuserlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandwritingSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='handwriting_samples/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('dyslexia_score', models.FloatField(blank=True, null=True)),
                ('interpretation', models.CharField(blank=True, max_length=50, null=True)),
                ('letter_counts', models.JSONField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handwriting_samples', to='users.student')),
            ],
        ),
    ]
