# Generated by Django 5.2.4 on 2025-07-28 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_handwritingsample'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentStageProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stage', models.IntegerField(default=1)),
                ('locked', models.BooleanField(default=False)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stage_progress', to='users.student')),
            ],
        ),
    ]
