# Generated by Django 5.2.4 on 2025-07-28 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_studentstageprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuserlink',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_links', to='users.student'),
        ),
    ]
