# Generated by Django 5.2.4 on 2025-07-28 19:59

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_studentuserlink_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='StageProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stage', models.IntegerField(default=1)),
                ('completed_stages', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stage_progress', to='users.student')),
            ],
        ),
        migrations.DeleteModel(
            name='StudentStageProgress',
        ),
    ]
