# Generated by Django 5.2.4 on 2025-09-07 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_studenttask'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cutoff_percentage', models.FloatField(help_text='Percentage cutoff for dyslexia indication')),
                ('total_score', models.FloatField()),
                ('total_max_score', models.FloatField()),
                ('percentage_score', models.FloatField()),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk')], max_length=10)),
                ('dyslexia_indication', models.BooleanField(default=False)),
                ('summary_notes', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to=settings.AUTH_USER_MODEL)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_summary', to='users.student')),
            ],
        ),
    ]
