# Generated by Django 5.2.4 on 2025-09-07 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_assessmentsummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=255)),
                ('activity_type', models.CharField(choices=[('reading', 'Reading Exercise'), ('writing', 'Writing Practice'), ('phonics', 'Phonics Training'), ('memory', 'Memory Enhancement'), ('coordination', 'Hand-Eye Coordination'), ('visual', 'Visual Processing'), ('auditory', 'Auditory Processing'), ('cognitive', 'Cognitive Training')], max_length=20)),
                ('description', models.TextField(help_text='Detailed description of the activity')),
                ('instructions', models.TextField(help_text='Step-by-step instructions for implementation')),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('bi-weekly', 'Twice a Week'), ('monthly', 'Monthly')], max_length=20)),
                ('duration_minutes', models.IntegerField(help_text='Duration of each session in minutes')),
                ('target_audience', models.CharField(choices=[('teacher', 'Teacher Implementation'), ('parent', 'Parent Implementation'), ('both', 'Both Teacher and Parent')], max_length=10)),
                ('expected_outcomes', models.TextField(help_text='Expected outcomes and improvements')),
                ('success_criteria', models.TextField(blank=True, help_text='How to measure success')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_activities', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_assignments', to='users.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
