# Generated by Django 5.2.4 on 2025-09-07 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_activityassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField()),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('missed', 'Missed Session'), ('paused', 'Paused')], default='not_started', max_length=20)),
                ('performer', models.CharField(choices=[('teacher', 'Teacher'), ('parent', 'Parent')], max_length=10)),
                ('duration_actual', models.IntegerField(blank=True, help_text='Actual duration in minutes', null=True)),
                ('completion_percentage', models.IntegerField(default=0, help_text='Completion percentage (0-100)')),
                ('notes', models.TextField(blank=True, help_text='Session notes and observations')),
                ('challenges', models.TextField(blank=True, help_text='Any challenges encountered')),
                ('improvements', models.TextField(blank=True, help_text='Observed improvements')),
                ('student_engagement', models.IntegerField(default=5, help_text='Student engagement level (1-10)')),
                ('difficulty_level', models.IntegerField(default=5, help_text='Perceived difficulty for student (1-10)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='users.activityassignment')),
                ('recorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorded_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-session_date'],
                'unique_together': {('activity_assignment', 'session_date', 'performer')},
            },
        ),
    ]
