# Generated by Django 5.2.4 on 2025-09-07 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_activityprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handwriting_analysis_summary', models.TextField(help_text='Summary of handwriting analysis results')),
                ('task_performance_summary', models.TextField(help_text='Summary of task performance and scores')),
                ('activity_progress_summary', models.TextField(help_text='Summary of therapeutic activity progress')),
                ('final_diagnosis', models.CharField(choices=[('no_dyslexia', 'No Dyslexia Indicated'), ('mild_dyslexia', 'Mild Dyslexia'), ('moderate_dyslexia', 'Moderate Dyslexia'), ('severe_dyslexia', 'Severe Dyslexia'), ('requires_further_assessment', 'Requires Further Assessment')], max_length=30)),
                ('diagnosis_confidence', models.IntegerField(default=1, help_text='Confidence level (1-10)')),
                ('supporting_evidence', models.TextField(help_text='Key evidence supporting the diagnosis')),
                ('intervention_priority', models.CharField(choices=[('low', 'Low Priority'), ('medium', 'Medium Priority'), ('high', 'High Priority'), ('urgent', 'Urgent')], max_length=10)),
                ('short_term_goals', models.TextField(help_text='Goals for the next 3-6 months')),
                ('long_term_goals', models.TextField(help_text='Goals for the next 1-2 years')),
                ('recommended_interventions', models.TextField(help_text='Specific intervention strategies')),
                ('follow_up_timeline', models.CharField(help_text='Recommended follow-up schedule', max_length=255)),
                ('monitoring_indicators', models.TextField(help_text='Key indicators to monitor progress')),
                ('teacher_recommendations', models.TextField(help_text='Specific recommendations for teachers')),
                ('parent_recommendations', models.TextField(help_text='Specific recommendations for parents')),
                ('clinical_notes', models.TextField(blank=True, help_text='Additional clinical observations')),
                ('referrals_needed', models.TextField(blank=True, help_text='Referrals to other specialists if needed')),
                ('case_completed', models.BooleanField(default=False)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_evaluations', to=settings.AUTH_USER_MODEL)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_evaluation', to='users.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
