# Generated by Django 5.2.4 on 2025-09-07 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_finalevaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalevaluation',
            name='therapy_decision',
            field=models.CharField(choices=[('terminate', 'Terminate Therapy (Student Cured)'), ('continue', 'Continue Therapy (Re-assign Activities)'), ('pending', 'Decision Pending')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='finalevaluation',
            name='therapy_session_number',
            field=models.PositiveIntegerField(default=1, help_text='Current therapy session number'),
        ),
        migrations.AddField(
            model_name='finalevaluation',
            name='therapy_termination_reason',
            field=models.TextField(blank=True, help_text='Reason for terminating therapy if applicable'),
        ),
        migrations.CreateModel(
            name='TherapySessionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_number', models.PositiveIntegerField()),
                ('activity_assignments_data', models.JSONField(help_text='Snapshot of assigned activities')),
                ('activity_progress_data', models.JSONField(help_text='Snapshot of activity progress records')),
                ('final_evaluation_data', models.JSONField(help_text='Snapshot of final evaluation')),
                ('session_start_date', models.DateTimeField(help_text='When this therapy session started')),
                ('session_end_date', models.DateTimeField(help_text='When this therapy session ended')),
                ('session_outcome', models.CharField(choices=[('terminated', 'Therapy Terminated (Cured)'), ('continued', 'Therapy Continued (Restarted)'), ('ongoing', 'Session Ongoing')], default='ongoing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='therapy_reports', to='users.student')),
            ],
            options={
                'ordering': ['-session_number'],
                'unique_together': {('student', 'session_number')},
            },
        ),
    ]
