# Generated by Django 5.2.4 on 2025-09-07 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_finalevaluation_therapy_decision_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalevaluation',
            name='parent_recommendations',
        ),
        migrations.RemoveField(
            model_name='finalevaluation',
            name='teacher_recommendations',
        ),
        migrations.CreateModel(
            name='StakeholderRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stakeholder_type', models.CharField(choices=[('teacher', 'Teacher'), ('parent', 'Parent')], max_length=10)),
                ('observations', models.TextField(help_text="Observations about the student's progress")),
                ('recommendations', models.TextField(help_text='Specific recommendations for continued support')),
                ('concerns', models.TextField(blank=True, help_text='Any concerns or areas needing attention')),
                ('positive_changes', models.TextField(blank=True, help_text='Positive changes observed')),
                ('support_needed', models.TextField(blank=True, help_text='Additional support needed')),
                ('therapy_session_number', models.PositiveIntegerField(default=1, help_text='Related therapy session')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stakeholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stakeholder_recommendations', to='users.student')),
            ],
            options={
                'ordering': ['-therapy_session_number', 'stakeholder_type'],
                'unique_together': {('student', 'stakeholder', 'therapy_session_number')},
            },
        ),
    ]
