# Generated by Django 5.2.4 on 2025-09-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_finalevaluation_parent_recommendations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityassignment',
            name='difficulty',
            field=models.CharField(default='medium', help_text='Activity difficulty level', max_length=20),
        ),
        migrations.AddField(
            model_name='activityprogress',
            name='score',
            field=models.IntegerField(blank=True, help_text='Score obtained out of 10', null=True),
        ),
    ]
